### ISSUE TITLE
stop on errors

### ISSUE THREAD

**Issue by zenfish** [ComputerCheeseOfficial/CC-FRU-tool#1]
When doing something as important as configuring a BMC, you might consider killing the execution of the script on errors (parsing, poorly formatted input, etc) - you could do this with this line near the top of the bash script -

`set -e`

Having a partial change would also be bad ;)

Keep up the great work on computer cheese!

**Comment by ComputerCheeseOfficial** [comment]
Hi @zenfish,

Thanks for your advice.
Would you like to help commit the code?

Regards,
Computer Cheease
