### ISSUE TITLE
Howto put BMC into write mode?

### ISSUE THREAD

**Issue by proxforge** [ComputerCheeseOfficial/CC-FRU-tool#4]
Hello CCO, 

thanks for the tool. Can you tell howto put the ipmi into write mode? I had to do this on a RS500A-E11-RS12U with the following command:

`root@PMX1:~/CC-FRU-tool# sudo ./fru.sh`
`Unable to send RAW command (channel=0x0 netfn=0xa lun=0x0 cmd=0x12 rsp=0xc1): Invalid command`
`root@PMX1:~/CC-FRU-tool# ipmitool raw 0x30 0x17 0x01`

after that it worked. Can you tell if the command 0x30 0x17 0x01 is always the same on each IPMI no matter what Board you use? If thats not the case can you tell howto find out what raw values should be used to get the bmc into write mode enabled? Is there a "common" workflow for doing that?

Thanks in advance.
Jonas

**Comment by ComputerCheeseOfficial** [comment]
Hello Jonas,

Refer to the [IPMI NetFn codes](https://computercheese.blogspot.com/p/blog-page_5.html), NetFn **0x30** is an OEM command. Seems let BMC into write mode is a mechanism by the server manufacturer.

Computer Cheese
